/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package role.based.shop.management.assignment.gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
